import logging


class RuleBasedExpenseCategorizer:
    def __init__(self):
        super().__init__()

    @staticmethod
    def _rule_based_categorization(description):
        categories = {
            "Groceries": [
                "WALMART",
                "WAL-MART",
                "HEB",
                "SUPER",
                "MERCADO",
                "GROCERY",
                "COSTCO COM",
                "COSTCO WHSE",
                "COSTCO HERMOSILLO",
                "SAMS",
                "LEY",
                "ABTS",
                "FRYS",
                "SAFEWAY",
                "DOLLAR",
                "BATHANDBODYWORKS",
                "bathandbodyworks",
                "FOOD CITY",
                "CTLP*CARRAZCO LLC",
                "LINDA VISTA",
                "SORIANA",
                "SQ *WATER MART",
                "SPROUTS",
                "REYES HERMOSILLO",
                "EL MARKET",
                "FRUTERIA",
                "DULCERIA",
                "ABTS LA CURVA",
                "PESCADERIA",
                "ABARROTES",
                "ALBERTSONS",
                "ALIMENTOS AL DETALLE",
            ],
            "Restaurants": [
                "RESTAURANT",
                "CAFE",
                "BURGER",
                "PIZZA",
                "DOGUITOS",
                "LOS",
                "KFC",
                "MCDONALD",
                "McDonalds",
                "SUSHI",
                "WINGS",
                "DAIRY QUEEN",
                "IN-N-OUT",
                "FIVE GUYS",
                "DENNY'S",
                "TACO",
                "LITTLE CAESARS",
                "RAISING CANES",
                "MICHOACANA",
                "PANIFICADORA",
                "DILA GUAYMAS",
                "TDA DE SERV MAR",
                "AZIAN",
                "VIP SAN JUDAS",
                "FONDA EL JAVIAN URES",
                "NEVERIA EL PATIO",
                "OXXO",
                "CHARLEYS PHILLY",
                "PRETZELS",
                "OLIVE GARDEN",
                "BEYOND BREAD",
                "CHICK-FIL-A",
                "PANDA EXPRESS",
                "CA*GIRO AGREGADOR",
                "ASIAN EXPRESS",
                "STEAKHOUSE",
                "TAQUERIA",
                "DLR MARKET",
                "ICE CREAM",
                "TIANA'S PALACE",
                "CHURRO",
                "ICE",
                "SNACK",
                "CANDY",
                "THE COVE ON HARBOR",
                "JACK IN THE BOX",
                "CAFFENIO",
                "MIYAGI",
                "COCINA",
                "PANADERIA",
                "POINTMP*OCHOAS",
                "CHICKENUEVO",
                "DINER",
                "DUNKIN",
                "BREW",
                "MARISCOS",
                "SARKU",
                "GOLDEN CORRAL",
                "CACHORIADAS",
                "CENADURIA",
                "PEI WEI",
                "BAKERY",
                "TABU",
                "CHABELON",
                "CA FUNG",
                "BUFFALO",
                "REST",
                "JUGOS",
                "MUSCERA",
                "QUESERIA",
                "STARBUCKS",
                "REYDEREYES",
                "ACO HERMOSILLO",
                "COMERCIAL GALO",
                "LILIANMICHEL",
                "CHURRERIAS",
                "ELPATIOMODELO",
                "OREGANOS",
                "GELATO",
                "FIRST WATCH",
                "REPOSTERI",
                "POLLO",
                "ASADERO",
                "CHEDDAR",
                "ITALIAN PEASANT",
                "Cracker Barrel",
                "EEGEES",
                "YOGIS GRILL",
                "BURRITO",
                "TUTTI FRUTTI",
                "HOTDOGS",
                "CAYOMANGO",
            ],
            "Pharmacy/Health": [
                "MEDICAL",
                "FARM",
                "GUAD",
                "PHARMACY",
                "FAR",
                "BIO PLASMA",
                "MB NAILS",
                "PLANET FITNESS",
                "BARBERIA",
                "ARIZONA COMMUNITY PHYSIC",
                "KATS",
                "DANIZA SAL",
                "WALGREENS",
            ],
            "Transport/Gas": [
                "GAS",
                "UBER",
                "LYFT",
                "TRANSPORTE",
                "GASOLINERA",
                "QT",
                "ARCO",
                "COP PARKING METER",
                "CIRCLE K",
                "SHELL OIL",
                "GAZPRO",
                "CHEVRON",
                "COSTCO GAS",
                "GASERV",
                "AUTOPIS",
                "ARCO",
                "SPEEDWAY 1169",
                "SPEEDWAY 46268",
            ],
            "Car Maintenance": [
                "GREASE MONKEY",
                "EMISSIONS",
                "Emissions",
                "TOMMYS EXPRESS",
                "CAR WASH",
                "CARWASH",
                "TIRES",
                "AUTOPART DETA",
            ],
            "Utilities": [
                "AZ MVD FEE",
                "TELMEX",
                "CFE",
                "AGUA",
                "INTERNET",
                "LUZ",
                "ELECTRICIDAD",
                "TUCSON WATER",
                "COX",
                "ATT*",
                "INTUIT",
                "COSTCO *ANNUAL RENEWAL",
                "Netflix",
                "PROGRESSIVE",
                "LAURA PILATES",
                "AT&T",
            ],
            "Home Improvement": [
                "HOME DEPOT",
                "1335 HERMOSILLO",
                "INTERCERAMIC",
                "WINDOW DEPOT",
                "LOWES",
                "SHERWIN-WILLIAMS",
                "FERRE",
                "ACE",
                "RUBBERIZED COAT",
                "COMEX",
                "HERRAJES",
                "MATERIALES",
            ],
            "Shopping": [
                "BURLINGTON",
                "DD'S DISCOUNTS",
                "ROSS STORES",
                "MARSHALLS",
                "AMAZON",
                "Amazon",
                "MERCADO",
                "SAVERS",
                "SQ *THANK YOU FROM BELLA",
                "T.J. MAXX",
                "SHOP",
                "TIENDA",
                "CLIP MX*FLORERIA Y REG",
                "NALLELY SOBERANES PELU",
                "BONANZA DEALS",
                "BPK*JUAN DE DIOS",
                "GOODWILL",
                "DHRMA BAKTHI",
                "TARGET",
                "KOMATSU STORE",
                "GIRLS ESTATE SALES",
                "HOBBY-LOBBY",
                "SALVATION ARMY",
                "TJMAXX",
                "FLEXI",
                "BIN STORE",
                "CLIP MX*LOS DEL RAIL",
                "VAEROBUS",
                "OFERTAS DE ARAM",
                "Google One",
                "KWICK PLAZA DILA",
                "MEGA EDER",
                "OLD NAVY",
                "H&M",
                "CASA DE CAMPO URES",
                "INTER-STATE STUDIO",
                "XTRAMATH",
                "PAPELERIA",
                "DILLARDS",
                "CHICAGO MUSIC STORE",
                "IREPAIR XPERT",
                "OUTLET",
                "Carrazco LLC",
                "TEXAS GENERAL STORE",
                "JCPENNEY",
            ],
            "Travel": [
                "VIVAAEROB",
                "HOLIDAY INN",
                "PSM PROSEPAGO",
                "HOTEL",
                "MUSEUM",
                "URBAN MILWAUKEE",
                "Localiza",
                "AIRBNB",
                "PARKMOBILE",
                "PARKING",
                "THE BRIDGE TRAVEL",
            ],
            "Digital Subscriptions": ["NETFLIX", "GOOGLE ONE", "EPICGAMES"],
            "Entertainment": [
                "AMC 2698 FOOTHILLS 15",
                "ANGEL WWW.ANGEL.COMUT",
                "CARNIVAL ONLINE PIMA",
                "TICKETS",
                "SKY PLACE",
                "CINEMARK",
                "KIDZANIA",
                "GRUTAS",
                "PARKS",
                "Elevate South Tucson",
            ],
            "Real State": [
                "AZ CORP COMMISSION",
                "DEVELOPMENT SERVICES",
                "UPS",
                "PIMA FEDERAL CREDIT",
                "USPS",
            ],
            "Payments": [
                "AUTOPAY AUTO-PMT",
            ],
        }
        desc = str(description)
        for cat, keywords in categories.items():
            if any(k in desc for k in keywords):
                return cat
        return "Other"

    def categorize_expenses(self, df):
        df["Category"] = df["Description"].apply(self._rule_based_categorization)
        return df
