import logging


class RuleBasedExpenseCategorizer:
    def __init__(self):
        super().__init__()

    @staticmethod
    def _rule_based_categorization(description):
        categories = {
            "Groceries": [
                "WALMART",
                "WAL-MART",
                "HEB",
                "SUPER",
                "MERCADO",
                "GROCERY",
                "COSTCO COM",
                "COSTCO WHSE",
                "COSTCO HERMOSILLO",
                "SAMS",
                "LEY",
                "ABTS",
                "FRYS",
                "SAFEWAY",
                "DOLLAR",
                "BATHANDBODYWORKS",
                "bathandbodyworks",
                "FOOD CITY",
                "CTLP*CARRAZCO LLC",
                "LINDA VISTA",
                "SORIANA",
                "SQ *WATER MART",
                "SPROUTS",
                "REYES HERMOSILLO",
                "EL MARKET",
                "FRUTERIA",
                "DULCERIA",
                "ABTS LA CURVA",
                "PESCADERIA",
                "ABARROTES",
                "ALBERTSONS",
                "ALIMENTOS AL DETALLE",
                "MERPAGO*LAPURAVIDA",
                "MERPAGO*SAMANTHABELTRA",
                "MERPAGO*EFREN",
                "MERPAGO*GRANCHINA",
                "CARNICERIA",
                "ABARR TACUPETITO",
                "WHOLEFDS SPE",
                "PILOT 593"
            ],
            "Reyna": [
                "Zelle Payment To Reyna"
            ],
            "Restaurants": [
                "RESTAURANT",
                "CAFE",
                "BURGER",
                "PIZZA",
                "DOGUITOS",
                "KFC",
                "MCDONALD",
                "McDonalds",
                "SUSHI",
                "WINGS",
                "DAIRY QUEEN",
                "IN-N-OUT",
                "FIVE GUYS",
                "DENNY'S",
                "TACO",
                "LITTLE CAESARS",
                "RAISING CANES",
                "MICHOACANA",
                "PANIFICADORA",
                "DILA GUAYMAS",
                "TDA DE SERV MAR",
                "AZIAN",
                "VIP SAN JUDAS",
                "FONDA EL JAVIAN URES",
                "NEVERIA EL PATIO",
                "OXXO",
                "CHARLEYS PHILLY",
                "PRETZELS",
                "OLIVE GARDEN",
                "BEYOND BREAD",
                "CHICK-FIL-A",
                "PANDA EXPRESS",
                "CA*GIRO AGREGADOR",
                "ASIAN EXPRESS",
                "STEAKHOUSE",
                "TAQUERIA",
                "DLR MARKET",
                "ICE CREAM",
                "TIANA'S PALACE",
                "CHURRO",
                "SNACK",
                "CANDY",
                "THE COVE ON HARBOR",
                "JACK IN THE BOX",
                "CAFFENIO",
                "MIYAGI",
                "COCINA",
                "PANADERIA",
                "POINTMP*OCHOAS",
                "CHICKENUEVO",
                "DINER",
                "DUNKIN",
                "BREW CITY BRAND",
                "MARISCOS",
                "SARKU",
                "GOLDEN CORRAL",
                "CACHORIADAS",
                "CENADURIA",
                "PEI WEI",
                "BAKERY",
                "TABU",
                "CHABELON",
                "CA FUNG",
                "BUFFALO",
                "REST",
                "JUGOS",
                "MUSCERA",
                "QUESERIA",
                "STARBUCKS",
                "REYDEREYES",
                "ACO HERMOSILLO",
                "COMERCIAL GALO",
                "LILIANMICHEL",
                "CHURRERIAS",
                "ELPATIOMODELO",
                "OREGANOS",
                "GELATO",
                "FIRST WATCH",
                "REPOSTERI",
                "POLLO",
                "ASADERO",
                "CHEDDAR",
                "ITALIAN PEASANT",
                "Cracker Barrel",
                "EEGEES",
                "YOGIS GRILL",
                "BURRITO",
                "TUTTI FRUTTI",
                "HOTDOGS",
                "HOT DOGS",
                "CAYOMANGO",
                "EL PARGO ROJO",
                "PIZZERIA",
                "PURO PA DELANTE",
                "COYOTAS DONA MARIA",
                "GIBSON GIRL ICE",
                "NIKKORI",
                "CUPBOP KINO",
                "SWEETTOMATOES",
                "BUFFET",
                "BISBEE BREAKFAST",
                "KRISPY KREME",
                "FOOD STAREVENT",
                "KE BURROS",
                "Payment To Rene",
                "Payment To Ulises",
                "Payment To Perro Loco Ajo",
                "Payment From Luz Venegas",
                "MARIA MAGDALENA,VALENZUELA/ROMO",
                "BRIANEN,BALDENEGRO/BALDENEGRO",
                "JOSE MARTIN,ACEVEDO/ACEVEDO"
            ],
            "Pharmacy/Health": [
                "MEDICAL",
                "FARM",
                "GUAD",
                "PHARMACY",
                "FAR",
                "BIO PLASMA",
                "MB NAILS",
                "PLANET FITNESS",
                "BARBERIA",
                "ARIZONA COMMUNITY PHYSIC",
                "KATS",
                "DANIZA SAL",
                "WALGREENS",
                "Planet Fitness",
                "GENERAL DE LA BELLEZA",
                "SHELO NABEL HERMOSILLO",
                "FITMAX",
                "PELUQUERO"
            ],
            "Transport/Gas": [
                "GAS",
                "UBER",
                "LYFT",
                "TRANSPORTE",
                "GASOLINERA",
                "QT",
                "ARCO",
                "COP PARKING METER",
                "CIRCLE K",
                "SHELL OIL",
                "GAZPRO",
                "CHEVRON",
                "COSTCO GAS",
                "GASERV",
                "AUTOPIS",
                "ARCO",
                "SPEEDWAY 1169",
                "SPEEDWAY 46268",
                "SPEEDWAY 46280",
                "RCH AEROPUERTO",
                "UBRPAGOSMEX"
            ],
            "Car Maintenance": [
                "GREASE MONKEY",
                "EMISSIONS",
                "Emissions",
                "TOMMYS EXPRESS",
                "CAR WASH",
                "CARWASH",
                "TIRES",
                "AUTOPART DETA",
                "CHAPMAN HONDA",
                "AUTOZONE",
                "O'REILLY"
            ],
            "Utilities": [
                "AZ MVD FEE",
                "TELMEX",
                "CFE",
                "AGUA",
                "INTERNET",
                "LUZ",
                "ELECTRICIDAD",
                "TUCSON WATER",
                "COX",
                "ATT",
                "INTUIT",
                "COSTCO *ANNUAL RENEWAL",
                "Netflix",
                "PROGRESSIVE",
                "LAURA PILATES",
                "AT&T",
                "Empire Vista Assn Dues",
                "EMPIRE 8145",
                "PAY-HOA ASSESSMENTS",
                "Dbamr.Cooper",
                "Honda Pmt",
                "Tep Corporate",
                "Southwest Gas Billpay",
                "GOB EDO SONORA",
                "Zelle Payment To 5204278933"
            ],
            "Home Improvement": [
                "HOME DEPOT",
                "1335 HERMOSILLO",
                "INTERCERAMIC",
                "WINDOW DEPOT",
                "LOWES",
                "SHERWIN-WILLIAMS",
                "FERRE",
                "FERR KIOSKO MORELOS",
                "ACE",
                "RUBBERIZED COAT",
                "COMEX",
                "HERRAJES",
                "MATERIALES",
                "PIPESO",
                "PROCONSA PROGRESO",
                "LOS REALES SCALES",
                "HARBOR FREIGHT"
            ],
            "Shopping": [
                "BURLINGTON",
                "DD'S DISCOUNTS",
                "ROSS STORES",
                "MARSHALLS",
                "AMAZON",
                "Amazon",
                "MERCADO",
                "SAVERS",
                "SQ *THANK YOU FROM BELLA",
                "T.J. MAXX",
                "SHOP",
                "TIENDA",
                "CLIP MX*FLORERIA Y REG",
                "NALLELY SOBERANES PELU",
                "BONANZA DEALS",
                "BPK*JUAN DE DIOS",
                "GOODWILL",
                "DHRMA BAKTHI",
                "TARGET",
                "KOMATSU STORE",
                "GIRLS ESTATE SALES",
                "HOBBY-LOBBY",
                "SALVATION ARMY",
                "TJMAXX",
                "FLEXI",
                "BIN STORE",
                "CLIP MX*LOS DEL RAIL",
                "VAEROBUS",
                "OFERTAS DE ARAM",
                "Google One",
                "KWICK PLAZA DILA",
                "MEGA EDER",
                "OLD NAVY",
                "H&M",
                "CASA DE CAMPO URES",
                "INTER-STATE STUDIO",
                "XTRAMATH",
                "PAPELERIA",
                "DILLARDS",
                "CHICAGO MUSIC STORE",
                "IREPAIR XPERT",
                "OUTLET",
                "Carrazco LLC",
                "TEXAS GENERAL STORE",
                "JCPENNEY",
                "CARTER'S",
                "MEGA EDER",
                "OADPRS MU",
                "ZAZUETA COMERCIAL",
                "POINTMP*REGALOS",
                "HABISTORE",
                "Nike US Stores",
                "TEKBUY",
                "COPPEL",
                "TELCEL HERMOSILLO",
                "Zelle Payment To Brianna",
            ],
            "Travel": [
                "VIVAAEROB",
                "HOLIDAY INN",
                "PSM PROSEPAGO",
                "HOTEL",
                "MUSEUM",
                "URBAN MILWAUKEE",
                "Localiza",
                "AIRBNB",
                "PARKMOBILE",
                "PARKING",
                "THE BRIDGE TRAVEL",
                "CASA/KINO",
                "ALMA ANAHI LIZARRAGA"
            ],
            "Digital Subscriptions": [
                "NETFLIX",
                "GOOGLE ONE",
                "EPICGAMES",
                "KWS AGE CHECK",
            ],
            "Entertainment": [
                "AMC 2698 FOOTHILLS 15",
                "ANGEL WWW.ANGEL.COMUT",
                "CARNIVAL ONLINE PIMA",
                "TICKETS",
                "SKY PLACE",
                "CINEMARK",
                "KIDZANIA",
                "GRUTAS",
                "PARKS",
                "Elevate South Tucson",
                "TCC",
                "UNVRS* TUCSON HOLID",
                "GALLEGOINTERMEDIAT"
            ],
            "Real State": [
                "AZ CORP COMMISSION",
                "DEVELOPMENT SERVICES",
                "UPS",
                "PIMA FEDERAL CREDIT",
                "USPS",
                "Bank of America Mortgage",
                "Canterbury Ranch Assn Dues",
                "Valencia Reserve Hoa Dues",
                "Pima Fcu Transfer",
                "Payment To Karina",
                "Payment To Ruben Soto",
                "Payment To D&C Maintenance LLC",
                "Payment To Carmen",
                "Payment To Ricardo",
                "Payment To Noe",
                "Payment To Francisco Herrera"
            ],
            "Transfers": [
                "AUTOPAY AUTO-PMT",
                "Citi Autopay Payment",
                "Recurring Transfer From Jpmorgan Chase Bank",
                "Wells Fargo Ifi DDA To DDA",
                "Transfer To Sav",
                "Xoom Debit",
                "Online Domestic Wire Transfer",
                "ATM Cash Deposit",
                "Zelle Payment From Rene",
                "Zelle Payment From Savannah",
                "PAGO RECIBIDO DE TESORED POR ORDEN DE MANUEL SALAS",
                "DIS.EFE.BANAMEX SAB MIRADOR",
                "DIS.EFE.BANAMEX EL MIRADOR 2"
            ],
            "Income": [
                "Modular Mining S Payroll",
                "Remote Online Deposit",
                "Costco Cash Reward",
                "Payment From Yolanda",
                "Payment From Carmen",
                "Payment From Yesenia",
                "Payment From Noe",
                "Payment From Jose",
                "Payment From Allan",
                "Tax Ref"
            ],
            "Papas": [
                "GRACIELA,CARDENAS/QUINTERO",
            ]
        }
        desc = str(description)
        for cat, keywords in categories.items():
            for k in keywords:
                if k in desc:
                    return cat
        print(f"Could not categorize '{desc}'")
        return "Other"

    def categorize_expenses(self, df):
        df["Category"] = df["Description"].apply(self._rule_based_categorization)
        # print description with amount and category for debugging
        # for index, row in df.iterrows():
        #     print(
        #         f"Date: {row['Date']},Description: {row['Description']}, Debit: {row['Debit']}, Credit: {row['Credit']}, Category: {row['Category']}"
        #     )
        return df
